name: CD Process
on:
  push:
    branches:
      - Main
jobs:
  build-app:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-action@v1
        with:
          java-version: '12.x'
      - name: Run Flutter Build
        run: flutter build apk
      - name: Upload Artifact
        uses: actions/upload-arctifact@v1
        with:
          name: release
          path: build/app/outputs/apk/release/app-release.apk