name: CI Process
on:
  push:
    branches:
      - Main
jobs:
  flutter-test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
         channel: 'stable'
      - name: Run Pub Get
        run: flutter pub get
      - name: Run Flutter Analyze
        run: flutter analyze
